# Generated by Django 3.0.3 on 2020-09-24 07:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200924_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 7, 40, 54, 221836, tzinfo=utc)),
        ),
    ]
