# Generated by Django 3.0.3 on 2020-09-24 08:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200924_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 8, 9, 16, 933824, tzinfo=utc)),
        ),
    ]
