# Generated by Django 3.0.3 on 2020-09-25 04:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200924_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 4, 56, 45, 832109, tzinfo=utc)),
        ),
    ]
