# Generated by Django 3.0.3 on 2020-09-25 05:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200925_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_remove',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 5, 36, 34, 273441, tzinfo=utc)),
        ),
    ]
