# Generated by Django 3.0.3 on 2020-09-25 10:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200925_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 10, 48, 42, 674558, tzinfo=utc)),
        ),
    ]
